### ISSUE TITLE
Open data UAT defect -3

### ISSUE THREAD

**Issue by ayienyusof** [R-D-Theta-Edge/ST#101]

**Comment by ayienyusof** [comment]
Landing Page > Open Data > Gas

Steps to Reproduce
Login to the system.
Navigate to the Landing Page.
Click on the Open Data menu item.
Select Gas.

Actual Result
The term "gagasan" is still used instead of "gegasan".
The label "a. Daftar Pemegang Perakuan Kekompeten Gas" is not updated to "a. Senarai Orang Kompeten Gas Berdaftar".
Inconsistent terminology and labels compared to the Electrical module.

Expected Result
The term "gagasan" should be replaced with "gegasan".
The label "a. Daftar Pemegang Perakuan Kekompeten Gas" should be replaced with "a. Senarai Orang Kompeten Gas Berdaftar".
Terminology and labels should be consistent with those used in the Electrical module.

**Comment by Shanaqi** [comment]
label dropdown found. gagasan not found
