### ISSUE TITLE
Compound Captcha

### ISSUE THREAD

**Issue by ayienyusof** [R-D-Theta-Edge/ST#107]
adakan 1 popup captcha bila user click button cari, then baru show the result of carian

**Comment by atinn95** [comment]
- please provide captcha api

**Comment by ayienyusof** [comment]
Team .net ST tengah nak providekan, nanti aku share kan balik

**Comment by ayienyusof** [comment]
function callsliderCaptcha() {
            // Initialize sliderCaptcha
            let captcha;

            function initializeCaptcha() {
                if (captcha) {
                    // Reset the captcha to clear the canvas
                    captcha.reset();
                } else {
                    captcha = sliderCaptcha({
                        id: 'slider-captcha',
                        offset: 5,
                        loadingText: 'Loading...',
                        failedText: '@SharedLocalizer.GetLocalizedHtmlString("UM_CaptchaFailed")',
                        barText: '@SharedLocalizer.GetLocalizedHtmlString("UM_CaptchaBarText")',
                        repeatIcon: 'fa fa-repeat',
                        onSuccess: function () {
                            // Enable the submit button
                            $('#submitLogin').prop('disabled', false);
                            // Hide the captcha slider
                            $('#slider-captcha').hide(400, function () {
                                // Reset captcha field styles
                                $('#captcha-field').css({ 'box-shadow': 'none', 'transform': 'scale(1.0)' });
                                // Show success message
                                $('#captchaIsSuccess').val('true');
                                $('#captchaModal').modal('hide');
                                //sweetalert2 loading while performing login
                                Swal.fire({
                                    title: 'Logging in',
                                    html: '<div class="text-center"><i class="fas fa-spinner fa-spin fa-3x"></i><p>Please wait...</p></div>',
                                    showConfirmButton: false,
                                    allowOutsideClick: false,
                                    willOpen: () => {
                                        performLogin(); // Start login process after showing SweetAlert2
                                    }
                                });

                            });
                        },
                        setSrc: function () {
                            // Set the captcha image source
                            return "/scripts/assets/img/captcha/Pic" + Math.round(Math.random() * 4) + ".jpg";
                        },
                        localImages: function () {
                            // Load local captcha images
                            return "/scripts/assets/img/captcha/Pic" + Math.round(Math.random() * 4) + ".jpg";
                        }
                    });
                }

                // Open the modal
                $('#captchaModal').modal('show');
            }

            // Call initializeCaptcha() to create a new captcha
            initializeCaptcha();
        }

**Comment by atinn95** [comment]
- can you include the library for captcha. thank you :)

**Comment by ayienyusof** [comment]
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

dorang guna benda ni for captcha

**Comment by Shanaqi** [comment]
Dah letak google captcha for temporary
