### ISSUE TITLE
Landing_Page_SIT_2 STATISTIC_APPLICANT_TRACKING

### ISSUE THREAD

**Issue by ayienyusof** [R-D-Theta-Edge/ST#146]

**Comment by ayienyusof** [comment]
Landing Page > Open Data > Download

After download all the information need to store in DB

**Comment by Shanaqi** [comment]
Dont know which DB to store.

**Comment by ayienyusof** [comment]
isi dalam table ni table STATISTIC_APPLICANT_TRACKING

**Comment by Shanaqi** [comment]
done
