### ISSUE TITLE
Landing_Page_SIT_17 Captcha

### ISSUE THREAD

**Issue by ayienyusof** [R-D-Theta-Edge/ST#161]

**Comment by ayienyusof** [comment]
Landing Page > Compound

At enter compound number there is Google Recaptcha

**Comment by Shanaqi** [comment]
Run this command in server "composer require anhskohbo/no-captcha"

**Comment by Shanaqi** [comment]
Minta domain atau url sbb nk kena setup dkt google. Nanti env letak ni NOCAPTCHA_SECRET="6LfOuB0qAAAAALXp4lrIEGcGfzI1wEY9TJqJd_Re"
NOCAPTCHA_SITEKEY="6LfOuB0qAAAAAGq4y-3xdG5qe2JjXfSRQsnuaFSO"

**Comment by Shanaqi** [comment]
done
