### ISSUE TITLE
Landing_Page_SIT_18 placeholder language

### ISSUE THREAD

**Issue by ayienyusof** [R-D-Theta-Edge/ST#162]

**Comment by ayienyusof** [comment]
Open Data > Electric

Defect:
1. Jenis Kompeten rename to Competency Type
2. Remove Double quote (") at the ROC Number
3. Details in placeholder should display in English

**Comment by Shanaqi** [comment]
1 and 2 done

**Comment by Shanaqi** [comment]
done
